const mongoose = require("mongoose");
const schema = mongoose.Schema();

const SiteSchema = new mongoose.Schema(
  {
    siteLogo: { type: String, default: "" },
    useWhiteLogo:{type:Boolean, default:false},
    privacyPolicyLink: { type: String, default:"" },
    termsOfServicesLink:{type:String, default:""},
    siteTitle: { type: String },
    siteFav: { type: String },
    mailEngine: { type: String, default: "" },
    SMTPServer:{type: String, default: "" },
    SMTPPort:{type: String, default: "" },
    SMTPMail:{type: String, default: "" },
    SMTPPassword:{type: String, default: "" },
    EmailSenderName:{type: String, default: "" },
    mailForm: { type: String, default: "" },
    emailSendName: { type: String, default: "" },
    supportMail: { type: String, default: "" },
    supportPhone: { type: String, default: "" },
    supportAddress: { type: String, default: "" },
    DPOPhone: { type: String, default: "" },
    DPOEmail: { type: String, default: "" },
    sendWelcomeMail: { type: Boolean, default: true },
    welcomeMail: { type: String, default: "" },
    privacyPolicy: { type: String, default: "" },
    termsOfServices: { type: String, default: "" },
    newUserWelcomeMailTitle: { type: String, default: "" },
    newUserWelcomeMail: { type: String, default: "" },
    activateUserAccountMail: { type: String, default: "" },
    adminWithdrawRequestMail: { type: String, default: "" },
    confirmWithdrawRequestMail: { type: String, default: "" },
    wthdrawRequestProcessedMail: { type: String, default: "" },
    userResetPasswordMail: { type: String, default: "" },
    masterCardStatus:{ type: Boolean, default: false },
    bitCoinStatus:{ type: Boolean, default: false },
    userResetPasswordConfirmationMail: { type: String, default: "" },
    userSubscriptionEExpirationMail: { type: String, default: "" },
    userNewIPDetectedMail: { type: String, default: "" },
    btcHeaderText: {type: String, default: "" },
    btcAddress: {type: String, default: "" },
    buyBTCLink: {type: String, default: "" },
    loginBackgroundColor: { type: String, default: "" },
    loginButtonColor: { type: String, default: "" },
    loginBackgroundImage:{type: String, default: ""},
    siteLogoWhite: { type: String, default: "" },
    appDescription: { type: String, default: "" },
    maintenanceMode: { type: Boolean, default: false },
    numberFormat: { type: String, default: "" },
    currencyPosition: { type: String, default: "" },
    switchChartTradingView: { type: Boolean, default: false },
    allowUsersswitchView: { type: Boolean, default: false },
    disableChart: { type: Boolean, default: false },
    enableGoogleAds: { type: Boolean, default: false },
    enableCookiePopup: { type: Boolean, default: false },
    enableDonation: { type: Boolean, default: false },
    enableAutoLanguage: { type: Boolean, default: false },
    enablePOEEditorLanguage: { type: Boolean, default: false },
    donationAddress: { type: String, default: "" },
    donationText: { type: String, default: "" },
    startWatchUserSignUp:{type:String,default:""},
    newIdentityTitle:{type:String,default:""},
    newIdentityWizardAdvert:{type:String,default:""},
    startWatchNewUserSignUp:{type:String,default:""},
    enableCookiePopupTitle:{type:String,default:""},
    blacklistedCountries: [],
    cookiePopupText: { type: String, default: "" },
    cookiePopupTitle: { type: String, default: "" },
    googleSlot: { type: String, default: "" },
    googleAdClient: { type: String, default: "" },
    googleAnalytics: { type: String, default: "" },
    POEditorAPIKeys: { type: String, default: "" },
    POEditorLanguage: { type: String, default: "" },
    siteLanguage: { type: String, default: "" },
    siteStartingCurrencyPair: { type: String, default: "" },
    yourMainColor: { type: String, default: "" },
    siteMenuType: { type: String, default: "" },
    showFooterBar: { type: Boolean, default: false },
    defaultThemeColor: { type: String, default: "" },
    userCanChangeTheme: { type: Boolean, default: false },
    showTimeInFooter: { type: Boolean, default: false },
    showContactInFooter: { type: Boolean, default: false },
    showCalcaulator: { type: Boolean, default: false },
    loginCarouselImage1: { type: String, default: "" },
    loginCarouselImage2: { type: String, default: "" },
    loginCarouselImage3: { type: String, default: "" },
    allowsignup: { type: Boolean, default: false },
    phoneNumberRequired: { type: Boolean, default: false },
    userNeedVerifyAccount: { type: Boolean, default: false },
    needCaptchaSignup: { type: Boolean, default: false },
    signWithGoogle: { type: Boolean, default: false },
    signInFacebook: { type: Boolean, default: false },
    googleRecaptchaSiteKey: { type: String, default: "" },
    googleRecaptchaSiteKeySecret: { type: String, default: "" },
    googleAppID: { type: String, default: "" },
    googleAppSecret: { type: String, default: "" },
    authorizationRedirectUrl: { type: String, default: "" },
    facebookAppId: { type: String, default: "" },
    facebookAppSecret: { type: String, default: "" },
    URIOauthValid: { type: String, default: "" },
    enableIdentitySystem: { type: Boolean, default: false },
    blockTradingWithoutIdentity: { type: Boolean, default: false },
    blockDepositeWithoutIdentityVerification: { type: Boolean, default: false },
    blockWithdrawWithoutIdentity: { type: Boolean, default: false },
    newIdentityWizardTitle: { type: String, default: "" },
    newIdentityStartButton: { type: String, default: "" },
    identityStepName: { type: String, default: "" },
    identityStepType: { type: String, default: "" },
    identityStepDescription: { type: String, default: "" },
    enableIdentityUploadWithWebCam: { type: String, default: "" },
    webCamDocumentRatio: { type: String, default: "" },
    identityDocumentName: { type: String, default: "" },
    documentIdentityList: { type: String, default: "" },
    paymentSuccessText : { type: String, default: "" },
    paymentRefPattern : { type: String, default: "" },
    paymentNeedsApproval: { type: Boolean, default: false },
    verificationDecinedNotificationemplate:{type:String,default:""},
    verificationApprovedNotificationemplate:{type:String,default:""},
    BTCAmount1:{type:Number,default:0},
    BTCAmount2:{type:Number,default:0},
    BTCAmount3:{type:Number,default:0},
    BTCQRCodeImg:{type:String,default:""},
    paymentMethods : [],
    liveTrade:{type:Boolean,default:false},
    depositeImg1:{type:String,default:""},
    depositeImg2:{type:String,default:""},
    depositeImg3:{type:String,default:""},
    depositeImg1Link:{type:String, default:""},
    depositeImg2Link:{type:String, default:""},
    depositeImg3Link:{type:String, default:""},
    minDepositAmount:{type:Number, default:0},
    maxDepositAmount:{type:Number, default:0},
    minWithdrawalAmount:{type:Number, default:0},
    maxWithdrawalAmount:{type:Number, default:0},
    time: { type: Date, default: Date.now },
  },
  { collection: "site" }
);

const Model = mongoose.model("SiteSchema", SiteSchema);
module.exports = Model;
